name: Web-App Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build_and_test_web_app:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build web-app Docker container
        working-directory: web-app
        run: |
          docker build -t web-app:latest .

      - name: Run tests in web-app Docker container
        run: |
          docker run --rm web-app pytest /app/test_app.py --verbose

      - name: Cleanup Docker images
        run: |
          docker rmi web-app:latest
